# Site settings
title: Brendan O'Connor
description: > # this means to ignore newlines until "baseurl:"
  Brendan O'Connor's resume/CV/links to data/exegesis, in some fashion.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ussjoin.com" # the base hostname & protocol for your site
twitter_username: ussjoin
github_username:  ussjoin

# Build settings
markdown: kramdown
