# Site settings
title: Brendan O'Connor
description: > # this means to ignore newlines until "baseurl:"
  This is the CV and resume for Brendan O'Connor. If you'd like to talk about ways we could work together, please contact me: bfo@ussjoin.com.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ussjoin.com" # the base hostname & protocol for your site
twitter_username: ussjoin
github_username:  ussjoin

# Build settings
markdown: kramdown
